2nd module
js-tasks-ru/js-20220905_vladislav-koryakin pull request #2
Opened 2022-09-11 19:42 UTC by weepzip

2022-09-11 19:43 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-09-12 16:35 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    if (a.codePointAt(0) < 128 && b.codePointAt(0) > 128) {return 1;}
пожалуйста прочитайте главу из учебника про сортировку строк, ссылка есть в списке глав в задачнике к этой домашке

2022-09-12 16:35 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  if (param === 'desc') {sorted.reverse();}
от `reverse` следует избавиться и сортировать сразу в нужном порядке

2022-09-12 16:35 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  return Object.fromEntries(Object.entries(obj).filter(([key, value]) => fields.includes(`${key}`)));
👍 good

2022-09-12 16:35 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +  return Object.fromEntries(Object.entries(obj).filter(([key, value]) => !fields.includes(`${key}`)));
👍 good

2022-09-12 16:36 UTC, dosandk requested changes
решение `sortStrings` следует поправить

2022-09-12 20:27 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-09-14 21:24 UTC, dosandk approved these changes
good 👍

2022-09-14 21:24 UTC, merged